### ISSUE TITLE
REQ: Shizuku Support

### ISSUE THREAD

**Issue by sanctimoniousape** [aleksey-saenko/TTLChanger#3]
Don't know if this can be done (nor whether you'd be interested in doing so), but if there's any chance you could add support for going through Shizuku in lieu of requiring a rooted device I'm sure I'm not the only one who would be appreciative. 

Thanks for your time either way.

**Comment by aleksey-saenko** [comment]
Hello. Shizuku is not designed to provide root access. As stated on their website, it has two main purposes: 1 - Convenient way to use system APIs (there is no such api to change ttl); 2 - Convenient for the development of some apps that only requires ADB permissions. Yes, we can get more privileges because of ADB level access. However, this app indeed requires root level access to work.
